# Generated by Django 3.0.7 on 2020-06-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoBarras', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=50)),
                ('precoCusto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('precoVenda', models.DecimalField(decimal_places=2, max_digits=9)),
                ('unidadeMedida', models.CharField(max_length=2)),
                ('estoque', models.DecimalField(decimal_places=2, max_digits=9)),
                ('controlarEstoque', models.BooleanField()),
                ('descontoMaximo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
